declare module '@mui/icons-material' {
  import { SvgIconProps } from '@mui/material'
  
  export const LockOutlined: React.ComponentType<SvgIconProps>
  export const Dashboard: React.ComponentType<SvgIconProps>
  export const CalendarToday: React.ComponentType<SvgIconProps>
  export const People: React.ComponentType<SvgIconProps>
  export const Business: React.ComponentType<SvgIconProps>
  export const Person: React.ComponentType<SvgIconProps>
  export const Menu: React.ComponentType<SvgIconProps>
  export const Add: React.ComponentType<SvgIconProps>
  export const Edit: React.ComponentType<SvgIconProps>
  export const Delete: React.ComponentType<SvgIconProps>
  export const Search: React.ComponentType<SvgIconProps>
  export const FilterList: React.ComponentType<SvgIconProps>
  export const MoreVert: React.ComponentType<SvgIconProps>
  export const Close: React.ComponentType<SvgIconProps>
  export const Check: React.ComponentType<SvgIconProps>
  export const Warning: React.ComponentType<SvgIconProps>
  export const Info: React.ComponentType<SvgIconProps>
  export const Error: React.ComponentType<SvgIconProps>
  export const Success: React.ComponentType<SvgIconProps>
  export const Visibility: React.ComponentType<SvgIconProps>
  export const VisibilityOff: React.ComponentType<SvgIconProps>
  export const Email: React.ComponentType<SvgIconProps>
  export const Phone: React.ComponentType<SvgIconProps>
  export const LocationOn: React.ComponentType<SvgIconProps>
  export const Work: React.ComponentType<SvgIconProps>
  export const School: React.ComponentType<SvgIconProps>
  export const Home: React.ComponentType<SvgIconProps>
  export const Settings: React.ComponentType<SvgIconProps>
  export const AccountCircle: React.ComponentType<SvgIconProps>
  export const ExitToApp: React.ComponentType<SvgIconProps>
  export const Notifications: React.ComponentType<SvgIconProps>
  export const NotificationsNone: React.ComponentType<SvgIconProps>
  export const NotificationsActive: React.ComponentType<SvgIconProps>
  export const NotificationsOff: React.ComponentType<SvgIconProps>
  export const NotificationsBadge: React.ComponentType<SvgIconProps>
  export const NotificationsPaused: React.ComponentType<SvgIconProps>
  export const NotificationsNoneOutlined: React.ComponentType<SvgIconProps>
  export const NotificationsActiveOutlined: React.ComponentType<SvgIconProps>
  export const NotificationsOffOutlined: React.ComponentType<SvgIconProps>
  export const NotificationsBadgeOutlined: React.ComponentType<SvgIconProps>
  export const NotificationsPausedOutlined: React.ComponentType<SvgIconProps>
  export const NotificationsNoneRounded: React.ComponentType<SvgIconProps>
  export const NotificationsActiveRounded: React.ComponentType<SvgIconProps>
  export const NotificationsOffRounded: React.ComponentType<SvgIconProps>
  export const NotificationsBadgeRounded: React.ComponentType<SvgIconProps>
  export const NotificationsPausedRounded: React.ComponentType<SvgIconProps>
  export const NotificationsNoneSharp: React.ComponentType<SvgIconProps>
  export const NotificationsActiveSharp: React.ComponentType<SvgIconProps>
  export const NotificationsOffSharp: React.ComponentType<SvgIconProps>
  export const NotificationsBadgeSharp: React.ComponentType<SvgIconProps>
  export const NotificationsPausedSharp: React.ComponentType<SvgIconProps>
  export const NotificationsNoneTwoTone: React.ComponentType<SvgIconProps>
  export const NotificationsActiveTwoTone: React.ComponentType<SvgIconProps>
  export const NotificationsOffTwoTone: React.ComponentType<SvgIconProps>
  export const NotificationsBadgeTwoTone: React.ComponentType<SvgIconProps>
  export const NotificationsPausedTwoTone: React.ComponentType<SvgIconProps>
} 